version: '3.5'

services:

  registrar:
    image: "quay.io/coreos/etcd:v3.3"
    container_name: "etcd-registrar"
    restart: always
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: "3"
      CLIENT_ADDR: "etcd-registrar"
    volumes:
      - "${DOCKER_DATA:-/data/voxr-data}/etcd-keeper-etcd-data:/etcd-data"
    ports:
      - 32379:2379
      - 32380:2380
      - 34001:4001
    networks:
      - default
      - voxr_app_net

  etcdkeeper:
    # build: .
    image: hedzr/etcdkeeper
    # image: etcdkeeper
    container_name: "etcdkeeper-web-ui"
    restart: always
    environment:
      HOST: "0.0.0.0"
    ports:
      - 32000:8080
    depends_on:
      - registrar
    networks:
      - default
      - voxr_app_net

  cache:
    image: "hedzr/redis:5.0.5-mod"
    container_name: "cache-main-host"
    restart: always
    volumes:
      - "${DOCKER_DATA:-/data/voxr-data}/cache:/data"
      # - /myredis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/redis.conf"]
    ports:
      - "36379:6379"
    networks:
      - default
      - voxr_app_net

  db:
    image: "mysql:8"
    container_name: "db-master-host"
    environment:
    # my-secret-pw
    #MYSQL_ROOT_PASSWORD: "Bug#A99Izol"
    #MYSQL_DATABASE: iot_db
    restart: always
    volumes:
      - "${DOCKER_DATA:-/data/voxr-data}/mysql.conf.d:/etc/mysql/conf.d"
      - "${DOCKER_DATA:-/data/voxr-data}/mysql.data:/var/lib/mysql"
    ports:
      - "33306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    networks:
      - default
      - voxr_app_net

# https://severalnines.com/blog/mysql-docker-composing-stack

#  tool:
#    image: "ubuntu:bionic-mod"
#    command: ["ping", "registrar"]
#    depends_on:
#      - cache
#      - registrar
#      - etcdkeeper


networks:
  voxr_app_net:
    external: true

